project_id = "jdqiqzzziqkrnmjghrqd"

[functions.analyze-feedback]
verify_jwt = false

[functions.sync-to-notion]
verify_jwt = true

[functions.notify-slack]
verify_jwt = true

[functions.sync-to-jira]
verify_jwt = true